# Tyche Example - Biorefinery Toy Model

## Set up.

### One only needs to execute the following line once, in order to make sure recent enough packages are installed.

In [ ]:
#!pip install 'numpy>=1.17.2' 'pandas>=0.25.1'

### Import packages.

In [1]:
import os
import sys
sys.path.insert(0, os.path.abspath("../src"))

In [2]:
import numpy             as np
import matplotlib.pyplot as pl
import pandas            as pd
import re                as re

# The `tyche` package is located at <https://github.com/NREL/portfolio/tree/master/production-function/framework/src/tyche/>.
import tyche             as ty

## Load data.

### The data are stored in a set of tab-separated value files in a folder.

In [3]:
scenarios = ty.Designs("data/biorefinery")

### Compile the production and metric functions for each technology in the dataset.

In [4]:
scenarios.compile()

## Examine the data.

### The `functions` table specifies where the Python code for each technology resides.

In [5]:
scenarios.functions

,Style,Module,Capital,Fixed,Production,Metrics,Notes
Technology,,,,,,,
Biorefinery,numpy,biorefinery,capital_cost,fixed_cost,production,metrics,

### The `indices` table defines the subscripts for variables.

In [6]:
scenarios.indices

                                               Offset Description Notes
Technology  Type                Index
Biorefinery Capital             Conversion          2
                                Fermentation        1
                                Preprocessing       0
                                Separation          3
            Fixed               Insurance           1
                                Rent                0
            Input               Energy              1
                                Feedstock           0
            Metric              Jobs                0
            Output              Product             0
            Technical Parameter Conversion          1
                                Fermentation        0

### The `designs` table contains the cost, input, efficiency, and price data for a scenario.

In [7]:
scenarios.designs

                                                     Value  \
Technology  Scenario Variable          Index
Biorefinery Actual   Input             Energy         5000
                                       Feedstock      3000
                     Input efficiency  Energy         0.71
                                       Feedstock      0.82
                     Input price       Energy          0.5
                                       Feedstock        45
                     Lifetime          Conversion       25
                                       Fermentation     25
                                       Preprocessing    25
                                       Separation       25
                     Output efficiency Product         0.8
                     Output price      Product         600
                     Scale             NaN               1
            Ideal    Input             Energy         5000
                                       Feedstock      3000
                     Input efficiency  Energy         0.85
                                       Feedstock       0.9
                     Input price       Energy          0.5
                                       Feedstock        45
                     Lifetime          Conversion       25
                                       Fermentation     25
                                       Preprocessing    25
                                       Separation       25
                     Output efficiency Product        0.89
                     Output price      Product         600
                     Scale             NaN               1

                                                                           Units  \
Technology  Scenario Variable          Index
Biorefinery Actual   Input             Energy                     MJ/biorefinery
                                       Feedstock      tons feedstock/biorefinery
                     Input efficiency  Energy                                  1
                                       Feedstock                               1
                     Input price       Energy                             USD/MJ
                                       Feedstock               USD/ton feedstock
                     Lifetime          Conversion                           year
                                       Fermentation                         year
                                       Preprocessing                        year
                                       Separation                           year
                     Output efficiency Product                                 1
                     Output price      Product                   USD/ton product
                     Scale             NaN                      biorefinery/year
            Ideal    Input             Energy                     MJ/biorefinery
                                       Feedstock      tons feedstock/biorefinery
                     Input efficiency  Energy                                  1
                                       Feedstock                               1
                     Input price       Energy                             USD/MJ
                                       Feedstock               USD/ton feedstock
                     Lifetime          Conversion                           year
                                       Fermentation                         year
                                       Preprocessing                        year
                                       Separation                           year
                     Output efficiency Product                                 1
                     Output price      Product                   USD/ton product
                     Scale             NaN                      biorefinery/year

                                                     Notes
Technology  Scenario Variable          Index
Biorefinery Actual   Input             Energy
                                       Feedstock
                     Input efficiency  Energy
                                       Feedstock
                     Input price       Energy
                                       Feedstock
                     Lifetime          Conversion
                                       Fermentation
                                       Preprocessing
                                       Separation
                     Output efficiency Product
                     Output price      Product
                     Scale             NaN
            Ideal    Input             Energy
                                       Feedstock
                     Input efficiency  Energy
                                       Feedstock
                     Input price       Energy
                                       Feedstock
                     Lifetime          Conversion
                                       Fermentation
                                       Preprocessing
                                       Separation
                     Output efficiency Product
                     Output price      Product
                     Scale             NaN

### The `parameters` table contains additional techno-economic parameters for each technology.

In [8]:
scenarios.parameters

                                                     Offset Value     Units  \
Technology  Scenario Parameter
Biorefinery Actual   Capital cost for Conversion          5   750       USD
                     Capital cost for Fermentation        4  1500       USD
                     Capital cost for Preprocessing       3  1000       USD
                     Capital cost for Separation          6  1250       USD
                     Conversion yield                     1  0.81
                     Fermentation yield                   0   0.7
                     Fixed cost for Insurance             8  2000  USD/year
                     Fixed cost for Rent                  7  5000  USD/year
                     Jobs                                 2   2.0
            Ideal    Capital cost for Conversion          5   750       USD
                     Capital cost for Fermentation        4  1500       USD
                     Capital cost for Preprocessing       3  1000       USD
                     Capital cost for Separation          6  1250       USD
                     Conversion yield                     1  0.95
                     Fermentation yield                   0  0.82
                     Fixed cost   for Insurance           8  2000  USD/year
                     Fixed cost   for Rent                7  5000  USD/year
                     Jobs                                 2   4.0

                                                    Notes
Technology  Scenario Parameter
Biorefinery Actual   Capital cost for Conversion
                     Capital cost for Fermentation
                     Capital cost for Preprocessing
                     Capital cost for Separation
                     Conversion yield
                     Fermentation yield
                     Fixed cost for Insurance
                     Fixed cost for Rent
                     Jobs
            Ideal    Capital cost for Conversion
                     Capital cost for Fermentation
                     Capital cost for Preprocessing
                     Capital cost for Separation
                     Conversion yield
                     Fermentation yield
                     Fixed cost   for Insurance
                     Fixed cost   for Rent
                     Jobs

### The `results` table specifies the units of measure for results of computations.

In [9]:
scenarios.results

                                                 Units Notes
Technology  Variable Index
Biorefinery Cost     Cost              USD/biorefinery
            Metric   Jobs             jobs/biorefinery
            Output   Product  tons product/biorefinery

## Evaluate the designs in the dataset.

In [10]:
results = scenarios.evaluate_scenarios()

In [11]:
results

                                                   Value  \
Technology  Scenario Sample Variable Index
Biorefinery Actual   1      Cost     Cost    -549858.600
                            Metric   Jobs          2.000
                            Output   Product    1115.856
            Ideal    1      Cost     Cost    -992357.200
                            Metric   Jobs          4.000
                            Output   Product    1871.937

                                                                 Units
Technology  Scenario Sample Variable Index
Biorefinery Actual   1      Cost     Cost              USD/biorefinery
                            Metric   Jobs             jobs/biorefinery
                            Output   Product  tons product/biorefinery
            Ideal    1      Cost     Cost              USD/biorefinery
                            Metric   Jobs             jobs/biorefinery
                            Output   Product  tons product/biorefinery